### ISSUE TITLE
--jsonrpc-import is not working anymore

### ISSUE THREAD

**Issue by sickpig** [BitcoinUnlimited/ElectrsCash#132]
As of current master:HEAD (5448c1e657b76182e7fc8cd85f20f7c5f2ddfe23) using the above command line flag raise this error on start up

```
An unknown argument '--jsonrpc-import' was specified. 
```

**Comment by dagurval** [comment]
This is now the default. To disable json import, use `--no-json-import`.

This was not intended to break with v3, but sice it made it to the release, and it was a major version bump, I don't think it's worth updating now.

**Comment by sickpig** [comment]
thanks for clarifying @dagurval
