### ISSUE TITLE
Cannot initialize electrum server

### ISSUE THREAD

**Issue by PraneshASP** [BitcoinUnlimited/ElectrsCash#92]
Hi, I have a fully synced Bitcoin ABC node. When I try to build and run electrum server for the first time, the following error arises

Command : 

``` cargo run --release -- -vvv --timestamp --db-dir=./db --cookie="user:pass" --electrum-rpc-addr="127.0.0.1:50001" ```

Result :

```
  Finished release [optimized] target(s) in 0.08s
     Running `target/release/electrscash -vvv --timestamp --db-dir=./db '--cookie=user:pass' '--electrum-rpc-addr=127.0.0.1:50001'`
Config { log: StdErrLog { verbosity: Debug, quiet: false, show_level: true, timestamp: Millisecond, modules: [], writer: "stderr", color_choice: Auto }, network_type: bitcoin, db_path: "./db/mainnet", daemon_dir: "/home/user/.bitcoin", blocks_dir: "/home/user/.bitcoin/blocks", daemon_rpc_addr: V4(127.0.0.1:8332), electrum_rpc_addr: V4(127.0.0.1:50001), monitoring_addr: V4(127.0.0.1:4224), jsonrpc_import: false, index_batch_size: 100, bulk_index_threads: 2, tx_cache_size: 157286400, txid_limit: 100, server_banner: "Welcome to ElectrsCash 2.0.0 (Electrum Rust Server)!", blocktxids_cache_size: 157286400, rpc_timeout: 10, low_memory: false, cashaccount_activation_height: 563720, rpc_buffer_size: 2000 }
2020-09-19T12:18:28.396+00:00 - DEBUG - Server listening on 127.0.0.1:4224
2020-09-19T12:18:28.396+00:00 - DEBUG - Running accept thread
2020-09-19T12:18:28.396+00:00 - INFO - NetworkInfo { version: 220200, subversion: "/Bitcoin ABC:0.22.2(EB32.0)/", relayfee: 0.00001 }
2020-09-19T12:18:28.397+00:00 - INFO - BlockchainInfo { chain: "main", blocks: 653489, headers: 653489, verificationprogress: 0.9999967383503902, bestblockhash: "000000000000000002bfe12f983114e7585d363f7fb091b31a7517706c05a146", pruned: false, initialblockdownload: false }
2020-09-19T12:18:28.397+00:00 - DEBUG - opening DB at "./db/mainnet"
2020-09-19T12:18:28.408+00:00 - DEBUG - opening DB at "./db/mainnet"
2020-09-19T12:18:28.431+00:00 - INFO - listing block files at "/home/user/.bitcoin/blocks/blk*.dat"
2020-09-19T12:18:28.435+00:00 - INFO - indexing 1117 blk*.dat files
2020-09-19T12:18:28.435+00:00 - DEBUG - found 0 indexed blocks
2020-09-19T12:18:30.880+00:00 - ERROR - server failed: Error: getblockheader RPC error: {"code":-8,"message":"hash must be of length 64 (not 1, for '0')"}

```

How can I fix this? Kindly help.

**Comment by DaSpawn** [comment]
I am seeing this as well, any help would be great

**Comment by dagurval** [comment]
Thanks for opening the issue, unfortunately I missed it, so the late response.

This issue is likely due to optimisation done in #79. I've reverted that change in #93. Could you check out latest master to see if the issue is solved @PraneshASP @DaSpawn ?

**Comment by DaSpawn** [comment]
Looks to be working now, thanks!

**Comment by Nodeberry** [comment]
Yes..it started syncing it seems. But how to execute RPC queries (like getting address balance and so on)?

**Comment by PraneshASP** [comment]
Yes. It started syncing it seems.

 How can I check the address balance using rpc query? Is there any documentation with all the available operations?

**Comment by dagurval** [comment]
> Looks to be working now, thanks!

Nice, thanks for testing!

> Yes. It started syncing it seems.
> 
> How can I check the address balance using rpc query? Is there any documentation with all the available operations?

Great, the RPC interface is documented here: https://bitcoincash.network/electrum/protocol-methods.html

[Here is a minimalistic example](https://github.com/BitcoinUnlimited/ElectrsCash/blob/master/contrib/client.py) of how to do RPC queries, which you can test your server with `python3 client.py --server localhost "blockchain.address.get_balance" "bitcoincash:qq...."`

There are also some good client libraries out there in javascript and python that I know of if you're looking for more high level stuff.

**Comment by PraneshASP** [comment]
@dagurval Thanks for helping me out!

Also, it would be great if you can suggest some good JavaScript client libraries.

Cheers!

**Comment by dagurval** [comment]
The [electrum-cash](https://gitlab.com/GeneralProtocols/electrum-cash/library) is what I use. I have not tried it with localhost and without ssl (I use it with my public ElectrsCash server that has reverse SSL proxy), but according to the docs, this is how you connect:
```
const electrum = new ElectrumClient('Electrum client example', '1.4.1', ‘localhost’, 50001, ‘tcp’);
await electrum.connect(); 
const transactionID = '4db095f34d632a4daf942142c291f1f2abb5ba2e1ccac919d85bdc2f671fb251'; 
console.log(await electrum.request('blockchain.transaction.get', transactionID));
```

**Comment by PraneshASP** [comment]
Thank you @dagurval
