### ISSUE TITLE
Limit electrscash memory usage?

### ISSUE THREAD

**Issue by quangld** [BitcoinUnlimited/ElectrsCash#99]
Is there a setting that limits memory usage?
I'm not sure it's a memory leaked or not, but after a week of running, electrscash consumes all of memory than eventually not responding. I have to add a cronjob to restart it every week.
My PC has 16GB of memory + 4GB swap, running on i7-4770K, Ubuntu 20.04, Bitcoin Unlimited 1.9.0.1

**Comment by dagurval** [comment]
Yes, these options are available to tweak memory usage:

```
        --low-memory                       Indicate preference to less memory                                                                                 
                                                       usage over performance    

        --tx-cache-size-mb                   Total size of transactions to cache (MB)
        --blocktxids-cache-size-mb         Total size of block transactions IDs 
                                                                  to cache (in MB)
```

If you're using the Bitcoin Unlimited integration to start ElectrsCash, you can use the `electrum.rawarg` in bitcoin.conf to pass them on to ElectrsCash

For example:
```
electrum=1
electrum.rawarg=--tx-cache-size-mb=100
electrum.rawarg=--blocktxids-cache-size-mb=100
electrum.rawarg=--low-memory
```

**Comment by dagurval** [comment]
However, your system should be more than sufficient for running with the default options, so I will investigate memory usage. Thanks for submitting the issue.

**Comment by quangld** [comment]
let me know if you want the log file

**Comment by quangld** [comment]
My current config
```
prune=0
dbcache=4096
disablewallet=1
daemon=1
txindex=1
server=1
disablesafemode=1
excessiveblocksize=32000000
use-grapheneblocks=1
logips=0
electrum=1
electrum.host=0.0.0.0
```

**Comment by dagurval** [comment]
Could you test the latest version in the master branch?

If you manage to build the master branch (with `cargo build --release`), you can point Bitcoin Unlimited to use your build with `electrum.exec=<path_to_electrscash>/target/release/electrscash`.

I've made two changes that should affect memory usage. First one in #101 does an improved calculation of how much memory cached transactions take. The seconds one in #104 switches to jemalloc for memory allocation, which should avoid fragmentation and allows to track memory usage more accurately.

If you set up prometheus monitoring, you can observe over time how much memory electrscash is consuming. [I have done this for my server](https://stats.bitcoincash.network/graph?g0.range_input=2d&g0.expr=electrscash_process_jemalloc_allocated&g0.tab=0&g1.range_input=2d&g1.expr=electrscash_process_memory_rss&g1.tab=0). You should also be able to see it via the BU rpc command `getelectruminfo`.

**Comment by quangld** [comment]
Getting this error
`
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Msg("descriptor Desc { fq_name: \"electrscash_rockdb_mem_table_total_0x7ffe2d133d20\", help: \"Rockdb approximate memory usage of all the mem-tables\", const_label_pairs: [], variable_labels: [], id: 10979083314420163629, dim_hash: 9750785626157508783 } already exists with the same fully-qualified name and const label values")', src/metrics.rs:60:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by quangld** [comment]
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Msg("descriptor Desc { fq_name: \"electrscash_rockdb_mem_table_total_0x7ffea6ea2c50\", help: \"Rockdb approximate memory usage of all the mem-tables\", const_label_pairs: [], variable_labels: [], id: 11565758143039644809, dim_hash: 9750785626157508783 } already exists with the same fully-qualified name and const label values")', src/metrics.rs:60:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /usr/src/rustc-1.43.0/vendor/backtrace/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1063
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:204
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:224
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:470
  11: rust_begin_unwind
             at src/libstd/panicking.rs:378
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1222
  14: electrscash::metrics::Metrics::gauge_int
  15: electrscash::store::DBStore::open
  16: electrscash::main
  17: std::rt::lang_start::{{closure}}
  18: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  19: std::panicking::try::do_call
             at src/libstd/panicking.rs:303
  20: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:86
  21: std::panicking::try
             at src/libstd/panicking.rs:281
  22: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  23: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  24: main
  25: __libc_start_main
  26: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

**Comment by dagurval** [comment]
Thanks! Fixed in https://github.com/BitcoinUnlimited/ElectrsCash/commit/efcd3a48de64fe65c6591f836031e1e231f2b95d. Could you try again?

I was using memory location as a unique identifier... which in hindsight was not a good idea.

**Comment by quangld** [comment]
Running now, let's see how it goes. Thank

**Comment by dagurval** [comment]
Hey @quangld, do you have an update?

Here's my RAM usage. After the tx cache was filled, it flatted out.

![Screenshot 2020-12-04 at 13 13 54](https://user-images.githubusercontent.com/92707/101162515-bea9dd00-3632-11eb-8992-1d127abde915.png)

![Screenshot 2020-12-04 at 13 14 04](https://user-images.githubusercontent.com/92707/101162522-c1a4cd80-3632-11eb-879e-02055e83d484.png)

**Comment by quangld** [comment]
So far, no issue! My current graphs are just a couple days old (because the server was rebooted by power outage in my area)

**Comment by dagurval** [comment]
Thanks for the feedback. Closing based on feedback. Feel free to re-open if needed.
